<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="myfirst">

  <!-- ============================= -->
  <!-- 1. 파라미터 정의             -->
  <!-- ============================= -->
  <!-- 몸통 -->
  <xacro:property name="body_len"     value="0.6"/>
  <xacro:property name="body_radius"  value="0.2"/>
  <xacro:property name="base_mass"    value="10"/>

  <!-- 다리 -->
  <xacro:property name="leg_l"        value="0.6"/>
  <xacro:property name="leg_w"        value="0.1"/>
  <xacro:property name="leg_h"        value="0.2"/>
  <xacro:property name="leg_mass"     value="10"/>
  <xacro:property name="leg_z_offset" value="-0.3"/>

  <!-- 바퀴 -->
  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="wheel_width"  value="0.1"/>
  <xacro:property name="wheel_mass"   value="1"/>

  <!-- 조인트 오프셋 -->
  <xacro:property name="base_to_leg_y" value="0.22"/>
  <xacro:property name="base_to_leg_z" value="0.25"/>
  <xacro:property name="wheel_z_offset" value="-0.65"/>

  <!-- ============================= -->
  <!-- 2. 재사용 매크로 정의        -->
  <!-- ============================= -->

  <!-- leg 매크로: left/right 두 군데 사용 -->
  <xacro:macro name="leg" params="SIDE SIGN">
    <link name="${SIDE}_leg">
      <visual>
        <geometry>
          <box size="${leg_l} ${leg_w} ${leg_h}"/>
        </geometry>
        <origin xyz="0 0 ${leg_z_offset}" rpy="0 1.57 0"/>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="${leg_l} ${leg_w} ${leg_h}"/>
        </geometry>
        <origin xyz="0 0 ${leg_z_offset}" rpy="0 1.57 0"/>
      </collision>
      <inertial>
        <mass value="${leg_mass}"/>
        <inertia
          ixx="1e-3" ixy="0.0" ixz="0.0"
          iyy="1e-3" iyz="0.0"
          izz="1e-3"/>
      </inertial>
    </link>

    <!-- 몸통↔다리 고정 조인트 -->
    <joint name="base_to_${SIDE}_leg" type="fixed">
      <parent link="base_link"/>
      <child  link="${SIDE}_leg"/>
      <origin xyz="0 ${SIGN * base_to_leg_y} ${base_to_leg_z}"/>
    </joint>
  </xacro:macro>

  <!-- wheel 매크로: left/right 앞바퀴 -->
  <xacro:macro name="front_wheel" params="SIDE">
    <link name="${SIDE}_front_wheel">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.57 0 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.57 0 0"/>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="1e-3" ixy="0.0" ixz="0.0"
          iyy="1e-3" iyz="0.0"
          izz="1e-3"/>
      </inertial>
    </link>

    <!-- 다리↔바퀴 회전 조인트 -->
    <joint name="${SIDE}_front_wheel_joint" type="continuous">
      <parent link="${SIDE}_leg"/>
      <child  link="${SIDE}_front_wheel"/>
      <origin xyz="0 0 ${wheel_z_offset}"/>
      <!-- Y축으로 회전 -->
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- ============================= -->
  <!-- 3. 실제 로봇 구성            -->
  <!-- ============================= -->

  <!-- 몸통 -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${body_len}" radius="${body_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${body_len}" radius="${body_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${base_mass}"/>
      <inertia
        ixx="1e-3" ixy="0.0" ixz="0.0"
        iyy="1e-3" iyz="0.0"
        izz="1e-3"/>
    </inertial>
  </link>

  <!-- 오른쪽 다리와 앞바퀴 -->
  <xacro:leg SIDE="right" SIGN="-1"/>
  <xacro:front_wheel SIDE="right"/>

  <!-- 왼쪽 다리와 앞바퀴 -->
  <xacro:leg SIDE="left"  SIGN="1"/>
  <xacro:front_wheel SIDE="left"/>

</robot>
