#!/usr/bin/env python3

import rospy
from std_msgs.msg import Header
from std_msgs.msg import String

class Mpub:
    def __init__(self):
        self.pub_01 = rospy.Publisher('message', String, queue_size=10)
        rospy.Timer(rospy.Duration(secs= 2.0), self.print_hello)
        self.msg = String()
    def print_hello(self, _event):
        self.msg.data = f"hello, ROS! noetic {self.i}"
        self.i += 1
        self.i += 1
        rospy.loginfo(self.msg.data)
        self.pub_01.publish(self.msg)
    


def main():
    rospy.init_node('mpub')
    node = Mpub()
    while not rospy.is_shutdown():
        rospy.spin()

if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass